[project]
name = "cnquant-dependencies"
version = "0.1.0"
description = "This repository contains the dependencies shared by more than one of the CnQuant applications"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = []
