[project]
name = "cnquant-dependencies"
version = "0.2.8"
description = "This repository contains the dependencies shared by more than one of the CnQuant applications"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "numpy>=1.26.4",
]
